version: '3.8'

services:
  whatsapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./.wwebjs_auth:/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - CHROME_PATH=/usr/bin/google-chrome
      - MAX_CONNECTIONS=10
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G