version: '3.8'

name: whatsapp-server-dev

services:
  whatsapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-server-dev
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./.wwebjs_auth:/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - CHROME_PATH=/usr/bin/chromium-browser
      - MAX_CONNECTIONS=10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      - whatsapp_net
    labels:
      - "com.whatsapp.server=development"
      - "com.whatsapp.description=WhatsApp Web API Server"
      - "com.whatsapp.version=1.0.0"

networks:
  whatsapp_net:
    driver: bridge
    name: whatsapp_dev_network
    labels:
      - "com.whatsapp.network=development"